# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(['policy', 'policyFile', 'policyString',
	'policyStringDestination', 'policySource', 'dictionary',
	'supportedFormats', 'defaultPolicyFile', 'urnPolicyFile'])
